#################################################################################
#                           Onebranch Retail Pipeline                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  ROOT: $(Build.SourcesDirectory)
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}

  WindowsContainerImage: 'cdpxwin1809.azurecr.io/global/vse2019:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      baseline:
        baselineFile: $(Build.SourcesDirectory)\.gdn\global.gdnbaselines
        suppressionSet: default
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
        suppressionSet: default

      tsa:
        enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: $(Build.SourcesDirectory)\.config\PolicheckExclusion.xml

    stages:
    - stage: main
      jobs:
      - job: build
        pool:
          type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
        
        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs

          # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_outputDirectory: '$(Build.SourcesDirectory)\out'
          ob_symbolsPublishing_enabled: false # https://aka.ms/obpipelines/symbols

          # https://aka.ms/obpipelines/sdl
          ob_sdl_binskim_break: true # always break the build on binskim issues, even if TSA enabled. You can disable it by setting to 'false'
          ob_sdl_roslyn_break: true

          ob_sdl_baseline_baselineFile: $(Build.SourcesDirectory)\.gdn\global.gdnbaselines
          ob_sdl_baseline_baselineSet: default
          ob_sdl_suppression_suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
          ob_sdl_suppression_suppressionSet: default

        steps:
        - task: UseDotNet@2
          continueOnError: true
          inputs:
            packageType: 'sdk'
            version: '5.0.103'
            useGlobalJson: false
            performMultiLevelLookup: true
            workingDirectory: '$(Build.SourcesDirectory)'

        - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
          displayName: 'Setup BuildNumber'
          inputs:
            system: 'RevisionCounter'
            major: '1'
            minor: '1'
            exclude_commit: true

        - script: $(Build.SourcesDirectory)\init.cmd
          displayName: 'Initialize repo'

        - script: $(Build.SourcesDirectory)\clean.cmd
          displayName: 'Clean Output Directories'
          
        - script: $(Build.SourcesDirectory)\build.cmd
          displayName: 'Build Solutions'

        - script: $(Build.SourcesDirectory)\build-test.cmd
          displayName: 'Run Tests'